apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: karsajobs-ui
  name: karsajobs-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs-ui
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: karsajobs-ui
    spec:
      containers:
      - image: vikipranata/karsajobs-ui:latest
        name: karsajobs-ui
        env:
        - name: VUE_APP_BACKEND
          value: 10.1.1.11:30808
        # - name: VUE_APP_BACKEND
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: status.hostIP
        ports:
        - containerPort: 8000
        resources: {}
status: {}
