apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui-service
spec:
  selector:
    app: karsajobs-ui
  type: NodePort
  ports:
    - name: karsajobs-ui
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30808
