apiVersion: v1
kind: Service
metadata:
  name: prometheus-blackbox-exporter
  namespace: monitoring
spec:
  ports:
    - name: http
      port: 9115
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: prometheus-blackbox-exporter
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
spec:
  selector:
    app: prometheus-server
  type: NodePort
  ports:
    - port: 8080
      targetPort: 9090
      nodePort: 30000