kind: PersistentVolume
apiVersion: v1
metadata:
  name: hostpath-prometheus-server-pv
  labels:
    app: prometheus-server
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/prometheus-pod"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-prometheus-server-pvc
  namespace: monitoring
  labels:
    app: prometheus-server
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
