kind: PersistentVolume
apiVersion: v1
metadata:
  name: uptime-kuma-pvc-pv
  labels:
    app.kubernetes.io/name: uptime-kuma
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/uptime-kuma"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-pvc
  namespace: monitoring
  labels:
    app.kubernetes.io/name: uptime-kuma
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G